---
abstract: 'agent server for APNS'
author:
  - 'Songmu <y.songmu@gmail.com>'
build_requires:
  AnyEvent: 0
  AnyEvent::Socket: 0
  HTTP::Request::Common: 0
  Plack::Test: 0
  Test::More: 0.98
  Test::TCP: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: APNS-Agent
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  APNS::Agent:
    file: lib/APNS/Agent.pm
    version: 0.02
requires:
  AnyEvent::APNS: 0
  Cache::LRU: 0
  Class::Accessor::Lite::Lazy: 0.03
  Encode: 0
  Hash::Rename: 0
  JSON::XS: 0
  Log::Minimal: 0
  Plack::Loader: 0
  Plack::Request: 0
  feature: 0
  perl: 5.010
resources:
  bugtracker: https://github.com/Songmu/p5-APNS-Agent/issues
  homepage: https://github.com/Songmu/p5-APNS-Agent
  repository: git://github.com/Songmu/p5-APNS-Agent.git
version: 0.02
